require("plugin.plugins")
require("plugin.nvim-tree-cfg")
require("plugin.onedark-cfg")
require("plugin.telescope-cfg")
require("plugin.lualine-cfg")
-- require("plugin.navigator-cfg")
require("plugin.gitgutter-cfg")
require("plugin.treesitter-cfg")
require("plugin.autopairs-cfg")
require("plugin.fterm-cfg")
require("plugin.indent-blankline-cfg")
require("plugin.lsp")
require("plugin.bufferline-cfg")
require("plugin.notify-cfg")
require("plugin.projec-cfg")
