
alias vim="nvim"
alias vi="nvim"


plugins=(git
		 zsh-autosuggestions
		 zsh-syntax-highlighting
         z
)

export FZF_DEFAULT_OPTS="--ansi --preview-window 'right:60%' --preview 'bat --color=always --style=header,grid --line-range :300 {}'"
export FZF_DEFAULT_COMMAND='ag --hidden --ignore-dir={node_modules,build,.vscode,.git,.idea} -g ""'
source $ZSH/oh-my-zsh.sh

pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish

